# server:
#   port: 8080

# spring:
#   application:
#     name: Trip4HaNoi-BE

#   profiles:
#     active: "@spring.profiles.active@"

#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 20MB

#   datasource:
#     url: jdbc:mysql://localhost:3306/trip4hanoi
#     username: root
#     password: 1234
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#     show-sql: true
#     hibernate:
#       ddl-auto: update

# # Cấu hình chung cho tất cả môi trường
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

# logging:
#   level:
#     root: info
#     web: info
#     com.trip4hanoi.app: debug

# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true

# gemini:
#   api:
#     key: AIzaSyDT_JP0VrvzWW1fcourZ9NzGS9ApuhjuaY

# cloudinary:
#   cloud-name: dfvq2ckbi
#   api-key: 283211323636595
#   api-secret: pGxOZ7KcTVk76ETXvGsiWgPYtLQ



server:
  port: 8080

spring:
  application:
    name: Trip4HaNoi-BE
  
  profiles:
    active: "@spring.profiles.active@"

# Cấu hình chung cho tất cả các môi trường
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    web: info
    com.trip4hanoi.app: debug
