name: Trip4 Hanoi BE
run-name: ${{github.action}}
on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  ci-pipeline:
    runs-on:  ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: '123456'
          MYSQL_DATABASE: trip4hanoi
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Create Firebase Config File
        run: |
          mkdir -p src/main/resources
          echo '${{ secrets.FIREBASE_JSON }}' > src/main/resources/trip4hanoi-1a2ba-firebase-adminsdk-fbsvc-29ccb30801.json

      - name: Run test (Unit Test & Integration Test)
        env:
          MAIL: ${{ secrets.MAIL }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          API_KEY_OPEN_WEATHER: ${{ secrets.API_KEY_OPEN_WEATHER }}
          PAYOS_CLIENT_ID: ${{ secrets.PAYOS_CLIENT_ID }}
          PAYOS_API_KEY: ${{ secrets.PAYOS_API_KEY }}
          PAYOS_CHECKSUM_KEY: ${{ secrets.PAYOS_CHECKSUM_KEY }}
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/trip4hanoi
          DB_USERNAME: root
          DB_PASSWORD: '123456'
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: mvn test -Dspring.profiles.active=dev

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker hub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/trip-4-hanoi-be:latest    
                ${{secrets.DOCKER_USERNAME}}/backend-service:${{github.sha}}

